// Import Drizzle ORM utilities for declaring relations (one-to-many, many-to-one) between tables
import { relations } from "drizzle-orm";
// Import PostgreSQL-specific column types and table creators from Drizzle
import { boolean, json, pgTable, pgTableCreator, text, timestamp } from "drizzle-orm/pg-core";

// Create a custom table factory that prefixes every table name with "zara_" to namespace them in the database
export const createTable = pgTableCreator((name) => `zara_${name}`);

// ── Auth tables (managed by better-auth) ─────────────────────────────────────

// Define the "user" table for storing registered customer and admin accounts
export const user = pgTable("user", {
  // Primary key: a text UUID generated by better-auth
  id: text("id").primaryKey(),
  // Display name for the user (required)
  name: text("name").notNull(),
  // Email address, must be unique for login and communication
  email: text("email").notNull().unique(),
  // Whether the email has been verified; defaults to false on creation
  emailVerified: boolean("email_verified")
    .$defaultFn(() => false)
    .notNull(),
  // Optional avatar image URL from OAuth provider or uploaded
  image: text("image"),
  // Optional unique username for username-based login
  username: text("username").unique(),
  // Role string ("customer" or "admin"), defaults to "customer" at sign-up
  role: text("role").$defaultFn(() => "customer"),
  // Timestamp of when the user record was first created
  createdAt: timestamp("created_at")
    .$defaultFn(() => new Date())
    .notNull(),
  // Timestamp of the last update to this user record
  updatedAt: timestamp("updated_at")
    .$defaultFn(() => new Date())
    .notNull(),
});

// Define the "session" table for tracking active user sessions (used by better-auth)
export const session = pgTable("session", {
  // Primary key: a text UUID for the session
  id: text("id").primaryKey(),
  // When this session expires and becomes invalid
  expiresAt: timestamp("expires_at").notNull(),
  // Unique session token stored in cookies/headers for authentication
  token: text("token").notNull().unique(),
  // When the session was created
  createdAt: timestamp("created_at").notNull(),
  // When the session was last refreshed
  updatedAt: timestamp("updated_at").notNull(),
  // Optional IP address from which the session was created
  ipAddress: text("ip_address"),
  // Optional user-agent string from the browser that created the session
  userAgent: text("user_agent"),
  // Foreign key to the user who owns this session; cascade deletes when user is removed
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
});

// Define the "account" table for mapping OAuth provider accounts to local users (used by better-auth)
export const account = pgTable("account", {
  // Primary key: a text UUID for this account link
  id: text("id").primaryKey(),
  // The account ID from the OAuth provider (e.g., GitHub user ID)
  accountId: text("account_id").notNull(),
  // The provider name (e.g., "github", "google", "credential")
  providerId: text("provider_id").notNull(),
  // Foreign key to the local user this provider account is linked to; cascade deletes
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  // OAuth access token for calling the provider's API on behalf of the user
  accessToken: text("access_token"),
  // OAuth refresh token used to obtain new access tokens when they expire
  refreshToken: text("refresh_token"),
  // OpenID Connect ID token containing the user's identity claims
  idToken: text("id_token"),
  // Timestamp after which the access token is no longer valid
  accessTokenExpiresAt: timestamp("access_token_expires_at"),
  // Timestamp after which the refresh token is no longer valid
  refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
  // OAuth scope string describing the permissions granted
  scope: text("scope"),
  // Hashed password for email/password credential accounts (null for OAuth-only users)
  password: text("password"),
  // When this account link was created
  createdAt: timestamp("created_at").notNull(),
  // When this account link was last updated
  updatedAt: timestamp("updated_at").notNull(),
});

// Define the "verification" table for email verification tokens and password reset tokens (used by better-auth)
export const verification = pgTable("verification", {
  // Primary key: a text UUID for this verification record
  id: text("id").primaryKey(),
  // Unique identifier for the verification (e.g., email address or user ID)
  identifier: text("identifier").notNull(),
  // The verification token or code value
  value: text("value").notNull(),
  // When this verification token expires
  expiresAt: timestamp("expires_at").notNull(),
  // When this verification record was created
  createdAt: timestamp("created_at").$defaultFn(() => /* @__PURE__ */ new Date()),
  // When this verification record was last updated
  updatedAt: timestamp("updated_at").$defaultFn(() => /* @__PURE__ */ new Date()),
});

// ── Business tables (prefixed with zara_) ────────────────────────────────────

// Define the "category" table using the custom prefix (zara_category) for organising products
export const category = createTable("category", (d) => ({
  // Auto-incrementing primary key generated by the database as identity
  id: d.integer().primaryKey().generatedByDefaultAsIdentity(),
  // Human-readable name of the category (e.g., "Floral", "Woody"), max 100 chars
  name: d.varchar({ length: 100 }).notNull(),
  // URL-friendly slug derived from the name, must be unique
  slug: d.varchar({ length: 100 }).notNull().unique(),
  // Optional longer description of the category for SEO and display
  description: d.text(),
  // Optional image URL for the category hero/banner
  image: d.text(),
  // Timestamp with timezone set on creation; auto-defaults to the current date
  createdAt: d
    .timestamp({ withTimezone: true })
    .$defaultFn(() => new Date())
    .notNull(),
  // Timestamp updated automatically whenever the row is modified
  updatedAt: d.timestamp({ withTimezone: true }).$onUpdate(() => new Date()),
}));

// Define the "product" table (zara_product) for perfume inventory items
export const product = createTable("product", (d) => ({
  // Auto-incrementing primary key generated by the database as identity
  id: d.integer().primaryKey().generatedByDefaultAsIdentity(),
  // Product name (e.g., "Noir Extreme"), max 256 characters
  name: d.varchar({ length: 256 }).notNull(),
  // Unique URL slug for the product detail page
  slug: d.varchar({ length: 256 }).notNull().unique(),
  // Rich-text or plain-text description of the fragrance
  description: d.text(),
  // Base price in cents (integer, so 9500 = $95.00)
  price: d.integer().notNull(),
  // JSON array of image URLs for the product gallery, typed as string[]
  images: json("images").$type<string[]>().default([]).notNull(),
  // JSON array of available size/price variants (e.g., [{ml:50, price:9500}])
  sizes: json("sizes").$type<{ ml: number; price: number }[]>().default([]).notNull(),
  // Text describing the scent profile and notes
  scentNotes: d.text(),
  // Foreign key to the category this product belongs to; set to null if the category is deleted
  categoryId: d.integer().references(() => category.id, { onDelete: "set null" }),
  // Current stock count; defaults to 0
  stock: d.integer().default(0).notNull(),
  // Flag to mark this product for display on the homepage featured section
  isFeatured: d.boolean().default(false).notNull(),
  // Timestamp of product creation, auto-set to the current date
  createdAt: d
    .timestamp({ withTimezone: true })
    .$defaultFn(() => new Date())
    .notNull(),
  // Timestamp auto-updated on every modification
  updatedAt: d.timestamp({ withTimezone: true }).$onUpdate(() => new Date()),
}));

// Define the "cart_item" table (zara_cart_item) for the shopping cart
export const cartItem = createTable("cart_item", (d) => ({
  // Auto-incrementing primary key
  id: d.integer().primaryKey().generatedByDefaultAsIdentity(),
  // Foreign key to the user who owns this cart item; cascade deletes with user
  userId: d
    .text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  // Foreign key to the product being added; cascade deletes with product
  productId: d
    .integer("product_id")
    .notNull()
    .references(() => product.id, { onDelete: "cascade" }),
  // The selected bottle size in millilitres (e.g., 50)
  size: d.integer().notNull(),
  // Quantity of this product selected; defaults to 1
  quantity: d.integer().default(1).notNull(),
  // Timestamp when the item was added to cart
  createdAt: d
    .timestamp({ withTimezone: true })
    .$defaultFn(() => new Date())
    .notNull(),
  // Timestamp of the last quantity or size change
  updatedAt: d.timestamp({ withTimezone: true }).$onUpdate(() => new Date()),
}));

// Define the "order" table (zara_order) for placed orders
export const order = createTable("order", (d) => ({
  // Auto-incrementing primary key
  id: d.integer().primaryKey().generatedByDefaultAsIdentity(),
  // Foreign key to the user who placed the order; cascade deletes with user
  userId: d
    .text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  // Order status: "pending", "paid", "shipped", "delivered", "cancelled"; defaults to "pending"
  status: d.varchar({ length: 20 }).default("pending").notNull(),
  // Total amount paid in cents, calculated from the sum of order items
  totalAmount: d.integer().notNull(),
  // Stripe Checkout session ID for reconciling payment events; unique if present
  stripeSessionId: d.text("stripe_session_id").unique(),
  // Recipient's full name for shipping
  shippingName: d.text("shipping_name"),
  // Street address line for shipping
  shippingAddress: d.text("shipping_address"),
  // City for shipping
  shippingCity: d.text("shipping_city"),
  // Postal/ZIP code for shipping
  shippingPostalCode: d.text("shipping_postal_code"),
  // Country for shipping
  shippingCountry: d.text("shipping_country"),
  // Timestamp when the order was placed
  createdAt: d
    .timestamp({ withTimezone: true })
    .$defaultFn(() => new Date())
    .notNull(),
  // Timestamp when the order was last updated (e.g., status change)
  updatedAt: d.timestamp({ withTimezone: true }).$onUpdate(() => new Date()),
}));

// Define the "order_item" table (zara_order_item) for line items within an order
export const orderItem = createTable("order_item", (d) => ({
  // Auto-incrementing primary key
  id: d.integer().primaryKey().generatedByDefaultAsIdentity(),
  // Foreign key to the parent order; cascade deletes with order
  orderId: d
    .integer("order_id")
    .notNull()
    .references(() => order.id, { onDelete: "cascade" }),
  // Foreign key to the product; set to null if the product is later deleted (preserves history)
  productId: d.integer("product_id").references(() => product.id, { onDelete: "set null" }),
  // Snapshot of the product name at the time of purchase (survives product deletion/rename)
  productName: d.text("product_name").notNull(),
  // Snapshot of the product image URL at the time of purchase
  productImage: d.text("product_image"),
  // Unit price in cents at the time of purchase
  price: d.integer().notNull(),
  // The bottle size in millilitres that was ordered
  size: d.integer().notNull(),
  // Quantity ordered of this item
  quantity: d.integer().notNull(),
  // Timestamp when this line item was created (same as the order time)
  createdAt: d
    .timestamp({ withTimezone: true })
    .$defaultFn(() => new Date())
    .notNull(),
}));

// ── Drizzle Relations ────────────────────────────────────────────────────────

// Define user relations: a user can have many accounts (OAuth links), sessions, cart items, and orders
export const userRelations = relations(user, ({ many }) => ({
  account: many(account),
  session: many(session),
  cartItems: many(cartItem),
  orders: many(order),
}));

// Define account relations: each account belongs to exactly one user
export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, { fields: [account.userId], references: [user.id] }),
}));

// Define session relations: each session belongs to exactly one user
export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, { fields: [session.userId], references: [user.id] }),
}));

// Define category relations: a category can have many products
export const categoryRelations = relations(category, ({ many }) => ({
  products: many(product),
}));

// Define product relations: a product belongs to one category and can appear in many cart items and order items
export const productRelations = relations(product, ({ one, many }) => ({
  category: one(category, { fields: [product.categoryId], references: [category.id] }),
  cartItems: many(cartItem),
  orderItems: many(orderItem),
}));

// Define cart item relations: each cart item belongs to one user and references one product
export const cartItemRelations = relations(cartItem, ({ one }) => ({
  user: one(user, { fields: [cartItem.userId], references: [user.id] }),
  product: one(product, { fields: [cartItem.productId], references: [product.id] }),
}));

// Define order relations: an order belongs to one user and can have many order items
export const orderRelations = relations(order, ({ one, many }) => ({
  user: one(user, { fields: [order.userId], references: [user.id] }),
  items: many(orderItem),
}));

// Define order item relations: each order item belongs to one order and optionally references one product
export const orderItemRelations = relations(orderItem, ({ one }) => ({
  order: one(order, { fields: [orderItem.orderId], references: [order.id] }),
  product: one(product, { fields: [orderItem.productId], references: [product.id] }),
}));
